version: '3.8'

services:

  task_app_db:
    container_name: task_app_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: taskapp
      POSTGRES_USER: taskapp
    ports:
      - 5432:5432
    volumes:
      - ./postgres_db/postgres-data:/var/lib/postgresql/data  

  task_api:
    container_name: task_app_api
    build:
      context: ./TaskAPI
    ports: 
      - "3000:3000"
    environment:
      - DB_HOST=task_app_db
    depends_on:
      - task_app_db
    restart: on-failure:10