version: '3.8'

services:

  postgres_db:
    container_name: task_app_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: taskapp
      POSTGRES_USER: taskapp
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  
